
AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Exclude:
    - test/prolog/use_cases/propose_edit_contribution_test.rb

Metrics/MethodLength:
  Exclude:
    - test/prolog/use_cases/propose_edit_contribution_test.rb

# New to 0.39.x

Style/NestedParenthesizedCalls:
  Enabled: false
